### ISSUE TITLE
Library not showing

### ISSUE THREAD

**Issue by aturtur** [rngtng/launchpad#6]
I installed this library, but it's not showing on my library browser. Tested Processing 2.2.1 and 1.5.1.
And I'm getting error: "The package 'com.rngtng' does not exist. You might be missing a library." when I try test example files. I'm running Windows 7 64bit.

**Comment by rngtng** [comment]
uh I havn't touched this project for long, especially with windows. Sounds like you have to instal the library first.

**Comment by aturtur** [comment]
Thanks for your reply! I have done exactly same way how you told to do in installation section (extracted launchpad-master.zip to under my Processing sketchbook/libraries folder and renamed launchpad-master folder to launchpad). I installed themidibus library just the same way without any problems. I also tried to install this on Mac (OSX Yosemite) and same problem appears.

I really want to get this library working. It's really interesting!
