### ISSUE TITLE
HOW TO USE THIS?

### ISSUE THREAD

**Issue by fillefilip8** [rngtng/launchpad#7]
IS THIS FOR JAVA OR NOT IM CONFUSED?????????????

**Comment by rngtng** [comment]
It's for [Processing](https://processing.org/) which is based on Java. How did you find about this Project?

**Comment by fillefilip8** [comment]
i was googleing and i was looking for a lib for JAVA not Processing.
Are you able to make a only Java version?

**Comment by rngtng** [comment]
I wish I could, but no time :(  but it shouldn't be a big deal, as a start look at https://github.com/rngtng/launchpad/blob/master/src/com/rngtng/launchpad/Launchpad.java and remove/replace all core processing classes, usually starting with `P` like `PApplet` ...

let me know if you need help..

**Comment by agrignard** [comment]
For a Java version I have been using this API that works well:
https://github.com/OlivierCroisier/LP4J

**Comment by rngtng** [comment]
@agrignard nice thx
